### ISSUE TITLE
Switching pages in the interface

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#3]
When you switch from the Extraction App page to the Example page, you lose everything you did on the previous page when you want to come back. It should be possible to keep it.

**Comment by santiagohy** [comment]
Hello, 
That's because there is no lemma that is statistically significant for those patterns P1 and P2.
But you are right, it would be good to know that there are no significant results. Maybe add also access to the p-values for each pattern tested. But I'm not sure how useful this information would be.

**Comment by perrier54** [comment]
An explanation message would be useful.

**Comment by perrier54** [comment]
I just realized that @santiagohy  answer does not correspond to the right issue.

**Comment by s-herrera** [comment]
The information is saved and will remain when you change pages.
The solution is not perfect, it may cause problems when correcting an already used pattern. In this case, a sign that the pattern was not changed would appear.  We are still looking for a better solution.
