### ISSUE TITLE
Non significant results

### ISSUE THREAD

**Issue by perrier54** [santiagohy/grammar-rules-extraction#5]
I load the corpus [fr_gsd-sud-train_sud.txt](https://github.com/santiagohy/grammar-rules-extraction/files/9243459/fr_gsd-sud-train_sud.txt) with the following patterns:
_P1: pattern{G[upos=ADJ]; D[upos=CCONJ]; D < G}
P2: pattern{G -[cc]-> D}
P3: D.lemma_
No result appears.

**Comment by s-herrera** [comment]
Hi, 
That's because there is no lemma that is statistically significant for those patterns P1 and P2.
But you are right, it would be good to know that there are no significant results. Maybe add also access to the p-values for each pattern tested. But I'm not sure how useful this information would be.

**Comment by perrier54** [comment]
An explanation message would be useful.

**Comment by s-herrera** [comment]
A message (info) will be display when there are no significant results.
